### ISSUE TITLE
NoMethodError: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by dblock** [dblock/iex-ruby-client#45]
```
E, [2019-04-18T20:06:03.984531 #232] ERROR -- : NoMethodError: undefined method `[]' for nil:NilClass
  /app/vendor/bundle/ruby/2.6.0/gems/iex-ruby-client-0.4.4/lib/iex/errors/client_error.rb:8:in `initialize'
  /app/vendor/bundle/ruby/2.6.0/gems/iex-ruby-client-0.4.4/lib/iex/resources/base.rb:9:in `exception'
  /app/vendor/bundle/ruby/2.6.0/gems/iex-ruby-client-0.4.4/lib/iex/resources/base.rb:9:in `raise'
  /app/vendor/bundle/ruby/2.6.0/gems/iex-ruby-client-0.4.4/lib/iex/resources/base.rb:9:in `rescue in symbol'
  /app/vendor/bundle/ruby/2.6.0/gems/iex-ruby-client-0.4.4/lib/iex/resources/base.rb:4:in `symbol'
  /app/vendor/bundle/ruby/2.6.0/gems/iex-ruby-client-0.4.4/lib/iex/resources/chart.rb:10:in `get'
```

via https://github.com/dblock/slack-market/issues/53

**Comment by dblock** [comment]
Pretty sure this is fixed via https://github.com/dblock/iex-ruby-client/commit/8d6cb856932cbcdc68bd9e0dbcd7cc8538101b25

Couldn't reproduce with a VCR recording ending with a `nil` body.
